### ISSUE TITLE
Not compiling LESS

### ISSUE THREAD

**Issue by glerner** [acarbone/AssetsMinify#35]
Plugin not catching LESS files, in my WordPress Multi-Site 

wp_enqueue_style('bootstrap', get_template_directory_uri() . '/less/bootstrap/bootstrap.less', array(), '3.3.4');
wp_enqueue_style('theme-base', get_template_directory_uri() . '/less/styles.less', array(), '0.1.0');

Generates links like this : 

<link rel='stylesheet' id='bootstrap-css'  href='http://mydomain.com/mymultisite/wp-content/themes/themename/less/bootstrap/bootstrap.less?ver=3.3.4' type='text/css' media='all' />

<link rel='stylesheet' id='theme-base-css'  href='http://mydomain.com/multisite/wp-content/themes/themename/less/styles.less?ver=0.1.0' type='text/css' media='all' />

/wp-content/uploads/sites/5/am_assets was created, remains empty (the Site ID for this site is 5)

/wp-content/uploads/am_assets I manually created, remains empty (checking if plugin not recognizing is Multi-Site and using the default uploads folder)

**Comment by glerner** [comment]
Made my new theme the active theme for the main admin site of the Multi-Site network. Browsing to the site gives me a white screen. 

PHP Fatal error:  Uncaught exception 'Exception' with message 'parse error: failed at `&:extend(.clearfix all);` /PATH/public_html/SUBDIR/wp-content/themes/THEME/less/bootstrap/mixins/grid.less on line 11' in /PATH/public_html/SUBDIR/wp-content/plugins/assetsminify/vendor/leafo/lessphp/lessc.inc.php:3460
Stack trace:
#0 /PATH/public_html/SUBDIR/wp-content/plugins/assetsminify/vendor/leafo/lessphp/lessc.inc.php(2273): lessc_parser->throwError()
#1 /PATH/public_html/SUBDIR/wp-content/plugins/assetsminify/vendor/leafo/lessphp/lessc.inc.php(121): lessc_parser->parse('// Grid system?...')
#2 /PATH/public_html/SUBDIR/wp-content/plugins/assetsminify/vendor/leafo/lessphp/lessc.inc.php(753): lessc->tryImport(Array, Object(stdClass), Object(stdClass))
#3 /PATH/public_html/SUBDIR/wp-content/plugins/assetsminify/vendor/leafo/lessphp/lessc.inc.php(162): lessc->compileProp(Array, Object(stdClass), Object(stdClass))
#4 /PATH/public_html/wp in /PATH/public_html/SUBDIR/wp-content/plugins/assetsminify/vendor/leafo/lessphp/lessc.inc.php on line 3460

leafo's lessphp does not work with current versions of LESS, see
https://github.com/leafo/lessphp/issues/503
and https://github.com/leafo/lessphp/issues/571

Even if you aren't going to update to a LESS compiler that supports LESS :extend, customize the compiler to catch the Exception so it doesn't crash PHP, okay? WordPress white screen isn't cool. (What if I didn't know how to enable logging PHP and WordPress debug messages?)

throwError('LESS :extend not supported, ignoring this code < -C-O-D-E line numbers in FILE>');

Temporary fix of course is grab LESS for an earlier Bootstrap that doesn't use :extend...

**Comment by glerner** [comment]
https://github.com/oyejorge/less.php has section on replacing the leafo lessc.inc.php with oyejorge lessc.inc.php and lib/ folder from oyejorge's less.php-master.zip

`require "less/lessc.inc.php";
    $less = new lessc;
    $less->addImportDir(array('less/','less/bootstrap/',__DIR__.'/', __DIR__.'/less/', __DIR__.'/less/bootstrap/'));
    try {
        $less->compileFile(__DIR__."/less/style.less", "/style.css");
    } catch (exception $e) {
        echo '<p>Error making CSS files: ' . $e->getMessage() .'</p>';
    }
`
Okay, back in business. Haven't tested it with AssetsMinify yet, but since Bootstrap LESS is compiling, AssetsMinify should work just fine (moving the files to the lessphp folder)
